<?php

$lang = array(

	'other' => 'เพิ่มเติม',
	'app_connect_ok' => 'เชื่อมต่อแล้ว ',
	'app_connect_false' => 'ขาดการเชื่อมต่อ',

	'note_deleteuser' => 'ลบผู้ใช้',
	'note_renameuser' => 'เปลี่ยนชื่อผู้ใช้',
	'note_deletefriend' => 'ลบเพื่อน',
	'note_gettag' => 'รับแท็ก',
	'note_getcreditsettings' => 'รับการตั้งค่าคะแนนแอปพลิเคชัน',
	'note_updatecreditsettings' => 'อัปเดตการตั้งค่าคะแนนแอปพลิเคชัน',
	'note_updateclient' => 'อัปเดตแอปพลิเคชันแคช',
	'note_updatepw' => 'อัปเดตรหัสผ่านผู้ใช้',
	'note_updatebadwords' => 'อัปเดตรายการตัวกรองคำ',
	'note_updatehosts' => 'อัปเดตรายการการวิเคราะห์ชื่อโดเมน',
	'note_updateapps' => 'อัปเดตรายการแอปพลิเคชัน',
	'note_updatetagtemplate' => 'อัปเดตการตั้งค่าเทมเพลตแท็ก',
	'note_list' => 'รายการแจ้งเตือน',
	'note_test' => 'ทดสอบ',
	'note_delete' => 'ลบทิ้ง',
	'note_succeed' => 'ประกาศที่ประสบความสำเร็จ ',
	'note_na' => 'ไม่แจ้ง',
	'note_false' => 'ความล้มเหลวในการแจ้งเตือน',
	'note_times' => 'ครั้ง',

	'pm_from' => 'จาก',
	'pm_to' => 'ส่งถึง',
	'pm_system' => 'ข้อมูลระบบ',
	'pm_date' => 'เวลา',
	'pm_daterange_1' => 'วันนี้',
	'pm_daterange_2' => 'เมื่อวาน',
	'pm_daterange_3' => 'สองวันก่อน',
	'pm_daterange_4' => 'อาทิตย์ที่แล้ว',
	'pm_daterange_5' => 'ก่อนหน้านี้',
	'pm_notitle' => '[ไม่มีชื่อ]',

	'user_add' => 'เพิ่มผู้ใช้',
	'user_delete' => 'ลบผู้ใช้',
	'login' => 'เข้าสู่ระบบ',
	'logout' => 'เลิก',
	'app_add' => 'เพิ่มแอปพลิเคชันใหม่',
	'app_delete' => 'ลบแอปพลิเคชัน',
	'app_edit' => 'แก้ไขแอปพลิเคชัน',
	'setting_update' => 'อัปเดตการตั้งค่าพื้นฐาน',
	'setting_register_update' => 'อัปเดตการตั้งค่าการลงทะเบียน',
	'pm_send' => 'ส่งข่าวสาธารณะ',
	'pm_delete' => 'ลบข่าวสาธารณะ',
	'pm_clear' => 'ทำความสะอาดข้อความ',
	'badword_add' => 'เพิ่มการกรองคำ',
	'badword_delete' => 'ลบคำว่าการกรอง',
	'admin_add' => 'เพิ่มผู้ดูแลระบบ',
	'admin_pw_edit' => 'แก้ไขรหัสผ่านของผู้ก่อตั้ง',
	'admin_priv_edit' => 'แก้ไขสิทธิ์ของผู้ดูแลระบบ',
	'domain_add' => 'เพิ่มการวิเคราะห์ชื่อโดเมน',
	'domain_delete' => 'ลบการวิเคราะห์ชื่อโดเมน',
	'credit_addexchange' => 'โครงการอัปเดตแผนการแลกเปลี่ยน',
	'credit_deleteexchange' => 'ลบโครงการแลกเปลี่ยนคะแนน',
	'credit_sync' => 'การตั้งค่าจุดสำหรับแอปพลิเคชันแบบซิงโครนัส',
	'db_export' => 'สำรองข้อมูล',
	'db_import' => 'การกู้คืนข้อมูล',
	'db_delete' => 'ลบข้อมูล',
	'note_delete' => 'ลบการแจ้งเตือน',
	'note_send' => 'การแจ้งเตือน',
	'dumpfile_exists' => 'การสำรอง',
	'dumpfile_not_exists' => 'ไม่มีการสำรองข้อมูล',
);